"""initial

Revision ID: 875b697ccea6
Revises: 
Create Date: 2021-09-03 11:13:13.998112

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "875b697ccea6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
