[default]
ALGORITHM='HS256'
MSG='Ambiente default'
REGEX_USERNAME='^([a-z]_\d){8,15}$'
# https://regex101.com/r/lvGxeH/1
REGEX_PASSWORD='^(?=(?:.*[a-z]){2})(?=(?:.*[A-Z]){2})(?=(?:.*\d){2})(?=(?:.*[@$!%*?&]){2})[A-Za-z\d@$!%*?&]{8,}$'
# openssl rand -hex 64
SECRET_KEY='0bc92d4f31500f1cf8fa53cf3c44dac5a804cc3a9534bf65aaf6db6ce8ba26c34d1da5c95a148b05595ef8127e78494ab2a451aefb812dd86ed5d90831d40c41'

[dev0]
MSG='Ambiente de desenvolvimento com Postgresql'
POSTGRES_DB = "main"
POSTGRES_USER = "admin"
POSTGRES_PASSWORD = "pwadmin"
DB_URL = 'postgresql+psycopg2://localhost/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}'

[development]
DB_URL = 'sqlite:///./dbdev.sqlite'
MSG='Ambiente de desenvolvimento'

[testing]
DB_URL = 'sqlite:///./dbtesting.sqlite'
SECRET_KEY='secret-key'
MSG='Ambiente de testes'

[production]
MSG='Ambiente de produção'
