"""full_name field.

Revision ID: 99b8586ea918
Revises: a3ad2d373dcb
Create Date: 2023-04-12 08:32:20.712513

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "99b8586ea918"
down_revision = "a3ad2d373dcb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade db."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade db."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
